server:
  port: 9084

spring:
  application:
    name: server
  cloud:
    nacos:
      discovery:
        server-addr: ehlxm.nacos.duowan.com:6801
        namespace: 4636c623-93b6-472b-8d48-f482aed74c98